### ISSUE TITLE
Exceptions Error Output in the Console

### ISSUE THREAD

**Issue by javierisaai** [RizkiMufrizal/Spring-OAuth2-Custom#2]
There seems to be a problem with the way the service is handling the requests. I am seeing many warnings and exceptions in the logs displayed by the command line. Please note I performed no change to your code. I simply started it and ran everything.

This is the command I am running to test your service:

`
curl -X POST -vu clientid:secret http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=admin&username=admin&grant_type=password&client_secret=secret&client_id=clientid"`

The compressed attachment contains the entire output from the command line at the time the above command was issued. Please review the output and let me know if there is anything I can provide to help.

If this should not be treated as an issue then please can you document an explanation and how to avoid the error output printed to the console.

[console.log.zip](https://github.com/RizkiMufrizal/Spring-OAuth2-Custom/files/758496/console.log.zip)

**Comment by RizkiMufrizal** [comment]
Hy javierisaai, sorry if my english is bad.
there problem because data additional_information in table oauth_client_details is empty, and now i add data additional_information in table oauth_client_details when the web is starting, checkout for data additional_information https://github.com/RizkiMufrizal/Spring-OAuth2-Custom/blob/master/src/main/java/com/rizki/mufrizal/spring/oauth2/custom/configuration/ScheduledTaskConfiguration.java#L81

**Comment by javierisaai** [comment]
Hello again! I fetched your changes and I no longer see the error output. The fact that you're processing the data now during the request is fixing the problem. Great job!

I'm attaching the log from my console, after testing your execution. No errors or exceptions are being logged.

I did encounter another problem. But I'll open a separate issue about it, so we can keep this isolated and simple + easier to track.

Cheers,
Javier

EDIT: your english is very acceptable, keep it up! 😄

[success.log.zip](https://github.com/RizkiMufrizal/Spring-OAuth2-Custom/files/761432/success.log.zip)
